### ISSUE TITLE
Setup workflow for deployments

### ISSUE THREAD

**Issue by StefanNemeth** [ls1intum/Helios#7]

**Comment by egekocabas** [comment]
**Update:** I am currently working on the default workflows that we need for development. When we have access to the VM, I will add a deployment workflow as well.

**Comment by egekocabas** [comment]
Working on to have a GitHub io page looks like this

![image](https://github.com/user-attachments/assets/01f96aa0-cd27-4063-bc44-c23d2e7f1b25)
